export const SAVE_VERSION = 7;

export const CARES = ["water", "mist", "prune"];

export const INVENTORY_CAPACITY = 12;

export const PRICE_BANDS = {
  quick: {
    label: "Quick",
    multiplier: 0.9,
  },
  fair: {
    label: "Fair",
    multiplier: 1,
  },
  boutique: {
    label: "Boutique",
    multiplier: 1.2,
  },
};

export const WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];

export const SPECIES = [
  {
    id: "button-fern",
    name: "Button Fern",
    traits: ["lush", "shade-loving"],
    price: 18,
    wholesaleCost: 9,
    shape: "fern",
    color: 0x5e945a,
    dryRate: 0.24,
    preferredLight: "shade",
    toleratedLight: ["indirect"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist", "prune"],
    unlockWeek: 1,
  },
  {
    id: "velvet-pothos",
    name: "Velvet Pothos",
    traits: ["trailing", "easygoing"],
    price: 20,
    wholesaleCost: 10,
    shape: "vine",
    color: 0x567a45,
    dryRate: 0.14,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "average",
    beneficialCare: ["water", "prune"],
    unlockWeek: 1,
  },
  {
    id: "pinstripe-calathea",
    name: "Pinstripe Calathea",
    traits: ["dramatic", "patterned"],
    price: 24,
    wholesaleCost: 12,
    shape: "fan",
    color: 0x386549,
    dryRate: 0.22,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist"],
    unlockWeek: 2,
  },
  {
    id: "pocket-succulent",
    name: "Pocket Succulent",
    traits: ["sunny", "sturdy"],
    price: 16,
    wholesaleCost: 8,
    shape: "succulent",
    color: 0x83a984,
    dryRate: 0.06,
    preferredLight: "sun",
    toleratedLight: ["indirect"],
    preferredHumidity: "dry",
    beneficialCare: ["water"],
    unlockWeek: 1,
  },
  {
    id: "little-monstera",
    name: "Little Monstera",
    traits: ["bold", "lush"],
    price: 26,
    wholesaleCost: 13,
    shape: "broad",
    color: 0x3d8050,
    dryRate: 0.17,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist", "prune"],
    unlockWeek: 2,
  },
  {
    id: "snake-plant",
    name: "Snake Plant",
    traits: ["upright", "easygoing"],
    price: 22,
    wholesaleCost: 11,
    shape: "spear",
    color: 0x718b3c,
    dryRate: 0.07,
    preferredLight: "indirect",
    toleratedLight: ["shade", "sun"],
    preferredHumidity: "dry",
    beneficialCare: ["water", "prune"],
    unlockWeek: 1,
  },
  {
    id: "moon-cactus",
    name: "Moon Cactus",
    traits: ["strange", "sunny"],
    price: 28,
    wholesaleCost: 14,
    shape: "cactus",
    color: 0x4f8c67,
    dryRate: 0.045,
    preferredLight: "sun",
    toleratedLight: ["indirect"],
    preferredHumidity: "dry",
    beneficialCare: ["water"],
    unlockWeek: 3,
  },
  {
    id: "string-of-pearls",
    name: "String of Pearls",
    traits: ["trailing", "sculptural"],
    price: 24,
    wholesaleCost: 12,
    shape: "pearls",
    color: 0x6f9b67,
    dryRate: 0.1,
    preferredLight: "indirect",
    toleratedLight: ["sun"],
    preferredHumidity: "dry",
    beneficialCare: ["water", "prune"],
    unlockWeek: 2,
  },
  {
    id: "coinleaf-pilea",
    name: "Coinleaf Pilea",
    traits: ["compact", "round-leaved"],
    price: 21,
    wholesaleCost: 10,
    shape: "coin",
    color: 0x64a65e,
    dryRate: 0.13,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "average",
    beneficialCare: ["water", "mist", "prune"],
    unlockWeek: 1,
  },
  {
    id: "rubber-plant",
    name: "Rubber Plant",
    traits: ["tall", "glossy"],
    price: 30,
    wholesaleCost: 15,
    shape: "tree",
    color: 0x315f45,
    dryRate: 0.11,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "average",
    beneficialCare: ["water", "mist", "prune"],
    unlockWeek: 3,
  },
  {
    id: "spoonflower-lily",
    name: "Spoonflower Lily",
    traits: ["flowering", "thirst-teller"],
    price: 25,
    wholesaleCost: 13,
    shape: "flower",
    color: 0x4f8c5d,
    dryRate: 0.25,
    preferredLight: "shade",
    toleratedLight: ["indirect"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist", "prune"],
    unlockWeek: 2,
  },
  {
    id: "parlor-palm",
    name: "Parlor Palm",
    traits: ["feathery", "graceful"],
    price: 27,
    wholesaleCost: 13,
    shape: "palm",
    color: 0x4f8051,
    dryRate: 0.16,
    preferredLight: "shade",
    toleratedLight: ["indirect"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist", "prune"],
    unlockWeek: 3,
  },
  {
    id: "zanzibar-gem",
    name: "Zanzibar Gem",
    traits: ["architectural", "easygoing"],
    price: 29,
    wholesaleCost: 14,
    shape: "gem",
    color: 0x416b3f,
    dryRate: 0.06,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "dry",
    beneficialCare: ["water", "prune"],
    unlockWeek: 4,
  },
  {
    id: "elephant-ear",
    name: "Elephant Ear",
    traits: ["oversized", "dramatic"],
    price: 32,
    wholesaleCost: 16,
    shape: "shield",
    color: 0x387556,
    dryRate: 0.26,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist"],
    unlockWeek: 4,
  },
  {
    id: "polka-dot-begonia",
    name: "Polka Dot Begonia",
    traits: ["spotted", "flowering"],
    price: 34,
    wholesaleCost: 17,
    shape: "cane",
    color: 0x527b55,
    dryRate: 0.18,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist", "prune"],
    unlockWeek: 5,
  },
  {
    id: "tiny-ficus",
    name: "Tiny Ficus",
    traits: ["miniature", "collectible"],
    price: 38,
    wholesaleCost: 20,
    shape: "bonsai",
    color: 0x47714a,
    dryRate: 0.12,
    preferredLight: "sun",
    toleratedLight: ["indirect"],
    preferredHumidity: "average",
    beneficialCare: ["water", "prune"],
    unlockWeek: 5,
  },
  {
    id: "pink-princess-vine",
    name: "Pink Princess Vine",
    traits: ["rare", "variegated", "trailing", "collectible"],
    price: 42,
    wholesaleCost: 25,
    shape: "pink-princess",
    color: 0x315d46,
    dryRate: 0.18,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist", "prune"],
    special: true,
    unlockWeek: 999,
  },
  {
    id: "jewel-orchid",
    name: "Jewel Orchid",
    traits: ["rare", "patterned", "compact", "collectible"],
    price: 44,
    wholesaleCost: 27,
    shape: "jewel-orchid",
    color: 0x24483e,
    dryRate: 0.21,
    preferredLight: "shade",
    toleratedLight: ["indirect"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist"],
    special: true,
    unlockWeek: 999,
  },
  {
    id: "spiral-aloe",
    name: "Spiral Aloe",
    traits: ["rare", "sculptural", "sunny", "collectible"],
    price: 48,
    wholesaleCost: 29,
    shape: "spiral-aloe",
    color: 0x719758,
    dryRate: 0.055,
    preferredLight: "sun",
    toleratedLight: ["indirect"],
    preferredHumidity: "dry",
    beneficialCare: ["water"],
    special: true,
    unlockWeek: 999,
  },
  {
    id: "blue-star-fern",
    name: "Blue Star Fern",
    traits: ["rare", "blue-toned", "feathery", "collectible"],
    price: 40,
    wholesaleCost: 24,
    shape: "blue-star",
    color: 0x5f8f83,
    dryRate: 0.2,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist", "prune"],
    special: true,
    unlockWeek: 999,
  },
];

export const CUSTOMERS = [
  {
    id: "mina",
    name: "Mina",
    color: 0xe39a7b,
    line: "My windowsill needs a little courage.",
    archetype: "decorator",
    budgetRange: [18, 32],
    unlockWeek: 1,
    returningLines: ["That brave little plant is thriving.", "I found one more corner that needs character."],
  },
  {
    id: "basil",
    name: "Basil",
    color: 0x7189a6,
    line: "I promised myself I could keep one alive.",
    archetype: "beginner",
    budgetRange: [14, 25],
    unlockWeek: 1,
    returningLines: ["Good news: the first one still has leaves.", "I think I am ready for plant number two."],
  },
  {
    id: "jo",
    name: "Jo",
    color: 0xd3a64b,
    line: "My bookshelf is looking emotionally vacant.",
    archetype: "small-space",
    budgetRange: [16, 29],
    unlockWeek: 1,
    returningLines: ["The bookshelf feels much less lonely now.", "I cleared another very small patch of shelf."],
  },
  {
    id: "nori",
    name: "Nori",
    color: 0x8f74a8,
    line: "I want a roommate who enjoys silence.",
    archetype: "practical",
    budgetRange: [17, 31],
    unlockWeek: 1,
    returningLines: ["My quiet roommate has been no trouble at all.", "I am back for something equally dependable."],
  },
  {
    id: "pip",
    name: "Pip",
    color: 0x6d9a78,
    line: "Something peculiar, but polite, please.",
    archetype: "collector",
    budgetRange: [23, 41],
    unlockWeek: 2,
    returningLines: ["Your last oddity has become the star of my collection.", "What curious specimen has appeared since my last visit?"],
  },
  {
    id: "sol",
    name: "Sol",
    color: 0xc9785e,
    line: "The sunniest corner of my flat is lonely.",
    archetype: "sun-seeker",
    budgetRange: [18, 34],
    unlockWeek: 1,
    returningLines: ["The sunny corner is practically glowing now.", "I have another bright sill ready for a resident."],
  },
  {
    id: "avery",
    name: "Avery",
    color: 0xc88aa0,
    line: "I need a gift that feels more alive than flowers.",
    archetype: "gift-giver",
    budgetRange: [20, 37],
    unlockWeek: 2,
    returningLines: ["The last gift was a complete triumph.", "I have another person who deserves something green."],
  },
  {
    id: "talia",
    name: "Talia",
    color: 0x779c9c,
    line: "My desk could use a colleague with better boundaries.",
    archetype: "office-keeper",
    budgetRange: [17, 32],
    unlockWeek: 2,
    returningLines: ["My leafy colleague is excellent in meetings.", "The reception desk is asking for similar company."],
  },
  {
    id: "ivo",
    name: "Ivo",
    color: 0xb88759,
    line: "There is still visible wall behind my plants. Unacceptable.",
    archetype: "maximalist",
    budgetRange: [25, 43],
    unlockWeek: 3,
    returningLines: ["The jungle is coming along splendidly.", "I found a gap between two leaves. Please help."],
  },
  {
    id: "mae",
    name: "Mae",
    color: 0x9a7fbc,
    line: "I enjoy the ritual of caring for something properly.",
    archetype: "careful-carer",
    budgetRange: [21, 39],
    unlockWeek: 3,
    returningLines: ["Your care advice has become part of my morning ritual.", "I am ready for a plant with a little more personality."],
  },
  {
    id: "omar",
    name: "Omar",
    color: 0x6788ad,
    line: "Show me the most plant I can get for my coins.",
    archetype: "bargain-hunter",
    budgetRange: [14, 28],
    unlockWeek: 4,
    returningLines: ["That was excellent value and an excellent plant.", "I have counted my coins. What is today's smart choice?"],
  },
  {
    id: "rue",
    name: "Rue",
    color: 0xa66e69,
    line: "I am looking for one exceptional specimen.",
    archetype: "connoisseur",
    budgetRange: [30, 50],
    unlockWeek: 5,
    returningLines: ["The specimen you chose rewards a closer look every day.", "Surprise me with something quietly extraordinary."],
  },
];

export const WEEKLY_OBJECTIVES = [
  {
    id: "healthy-margin",
    title: "Healthy Margins",
    description: "Finish the week with {target} coins of gross profit.",
    metric: "grossProfit",
    target: { base: 90, perWeek: 12, maximum: 260 },
    reward: { coins: 18, bloom: 6 },
  },
  {
    id: "new-windowsills",
    title: "New Windowsills",
    description: "Find homes for {target} plants this week.",
    metric: "plantsSold",
    target: { base: 11, perWeek: 1, maximum: 15 },
    reward: { coins: 16, bloom: 7 },
  },
  {
    id: "perfect-listener",
    title: "Perfect Listener",
    description: "Complete {target} perfect customer briefs.",
    metric: "perfectBriefs",
    target: { base: 4, perWeek: 1, maximum: 9 },
    reward: { coins: 12, bloom: 9 },
  },
  {
    id: "right-plant-right-light",
    title: "Right Plant, Right Light",
    description: "End {target} days with every displayed plant in tolerated or ideal light.",
    metric: "healthyDisplayDays",
    target: { base: 3, perWeek: 0, maximum: 5 },
    reward: { coins: 10, bloom: 8 },
  },
  {
    id: "thirst-rescue",
    title: "Tender Recovery",
    description: "Rescue {target} drooping plants with a good drink.",
    metric: "thirstRescues",
    target: { base: 3, perWeek: 0, maximum: 8 },
    reward: { coins: 10, bloom: 7 },
  },
  {
    id: "boutique-week",
    title: "Boutique Week",
    description: "Sell {target} plants at Boutique price to delighted customers.",
    metric: "boutiqueSales",
    // One honest Boutique-budget brief is guaranteed on each trading day. A
    // higher invariant would fail for a full migrated shop of the priciest
    // species: only one unlocked neighbor can afford that worst-case price.
    target: { base: 5, perWeek: 0, maximum: 5 },
    reward: { coins: 20, bloom: 5 },
  },
  {
    id: "quick-turnover",
    title: "Fresh Stock, Fast",
    description: "Rehome {target} Quick-priced plants.",
    metric: "quickSales",
    target: { base: 6, perWeek: 1, maximum: 12 },
    reward: { coins: 12, bloom: 6 },
  },
  {
    id: "variety-window",
    title: "A Varied Window",
    description: "Sell {target} different plant species this week.",
    metric: "uniqueSpeciesSold",
    target: { base: 5, perWeek: 1, maximum: 9 },
    reward: { coins: 14, bloom: 8 },
  },
  {
    id: "thoughtful-care",
    title: "Thoughtful Care",
    description: "Give plants {target} beneficial care moments.",
    metric: "beneficialCare",
    target: { base: 16, perWeek: 2, maximum: 40 },
    reward: { coins: 12, bloom: 8 },
  },
  {
    id: "familiar-faces",
    title: "Familiar Faces",
    description: "Delight {target} returning customers.",
    metric: "returningCustomersDelighted",
    target: { base: 3, perWeek: 1, maximum: 9 },
    reward: { coins: 15, bloom: 10 },
  },
];

// A brief generator chooses one required option, may choose a distinct preferred
// option, and positions the final budget inside the customer's personal range.
export const BRIEF_TEMPLATES = [
  {
    id: "all-quiet-corner",
    archetypes: "all",
    unlockWeek: 1,
    framing: "I need something calm for a quieter corner.",
    strategy: {
      required: { type: "trait", options: ["shade-loving", "easygoing"] },
      preferred: { type: "trait", options: ["lush", "glossy"], chance: 0.7, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.45 },
    },
  },
  {
    id: "all-sunny-sill",
    archetypes: "all",
    unlockWeek: 1,
    framing: "I have a bright sill waiting for the right plant.",
    strategy: {
      required: { type: "trait", options: ["sunny", "sturdy"] },
      preferred: { type: "trait", options: ["compact", "sculptural"], chance: 0.75, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.5 },
    },
  },
  {
    id: "all-soften-a-shelf",
    archetypes: "all",
    unlockWeek: 1,
    framing: "Could you soften the hard edges of my shelf?",
    strategy: {
      required: { type: "trait", options: ["trailing", "lush"] },
      preferred: { type: "trait", options: ["round-leaved", "patterned"], chance: 0.8, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.55 },
    },
  },
  {
    id: "all-upright-presence",
    archetypes: "all",
    unlockWeek: 1,
    framing: "I want a plant with a strong, upright presence.",
    strategy: {
      required: { type: "trait", options: ["upright", "bold"] },
      preferred: { type: "trait", options: ["dramatic", "architectural"], chance: 0.65, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.6 },
    },
  },
  {
    id: "all-gentle-routine",
    archetypes: "all",
    unlockWeek: 1,
    framing: "Please keep the care routine gentle and forgiving.",
    strategy: {
      required: { type: "trait", options: ["easygoing", "sturdy"] },
      preferred: { type: "trait", options: ["compact", "upright"], chance: 0.6, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.35 },
    },
  },
  {
    id: "all-rich-green",
    archetypes: "all",
    unlockWeek: 1,
    framing: "I am after deep, generous greens.",
    strategy: {
      required: { type: "trait", options: ["lush"] },
      preferred: { type: "trait", options: ["glossy", "trailing"], chance: 0.75, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.5 },
    },
  },
  {
    id: "all-pattern-play",
    archetypes: "all",
    unlockWeek: 2,
    framing: "Plain green is lovely, but today I want pattern.",
    strategy: {
      required: { type: "trait", options: ["patterned"] },
      preferred: { type: "trait", options: ["dramatic", "flowering", "spotted"], chance: 0.8, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.65 },
    },
  },
  {
    id: "all-flowering-lift",
    archetypes: "all",
    unlockWeek: 2,
    framing: "A little bloom would lift the whole room.",
    strategy: {
      required: { type: "trait", options: ["flowering"] },
      preferred: { type: "trait", options: ["graceful", "patterned"], chance: 0.65, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.6 },
    },
  },
  {
    id: "all-sculptural-oddity",
    archetypes: "all",
    unlockWeek: 2,
    framing: "Find me something that looks almost like a sculpture.",
    strategy: {
      required: { type: "trait", options: ["sculptural", "strange"] },
      preferred: { type: "trait", options: ["sunny", "trailing"], chance: 0.75, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.7 },
    },
  },
  {
    id: "all-tall-line",
    archetypes: "all",
    unlockWeek: 1,
    framing: "I need a vertical line to balance the room.",
    strategy: {
      required: { type: "trait", options: ["upright", "tall"] },
      preferred: { type: "trait", options: ["glossy", "architectural"], chance: 0.7, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.6 },
    },
  },
  {
    id: "all-soft-movement",
    archetypes: "all",
    unlockWeek: 1,
    framing: "I would love leaves with a little movement to them.",
    strategy: {
      required: { type: "trait", options: ["trailing", "feathery", "graceful"] },
      preferred: { type: "trait", options: ["lush", "round-leaved"], chance: 0.65, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.5 },
    },
  },
  {
    id: "all-clear-thirst-cues",
    archetypes: "all",
    unlockWeek: 2,
    framing: "I appreciate a plant that tells me clearly when it is thirsty.",
    strategy: {
      required: { type: "trait", options: ["thirst-teller"] },
      preferred: { type: "trait", options: ["flowering", "lush"], chance: 0.7, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.5 },
    },
  },
  {
    id: "all-tiny-treasure",
    archetypes: "all",
    unlockWeek: 1,
    framing: "I only have a little space, but it deserves a treasure.",
    strategy: {
      required: { type: "trait", options: ["compact", "miniature"] },
      preferred: { type: "trait", options: ["round-leaved", "collectible"], chance: 0.7, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.55 },
    },
  },
  {
    id: "all-dramatic-leaf",
    archetypes: "all",
    unlockWeek: 2,
    framing: "One dramatic leaf can change a whole corner.",
    strategy: {
      required: { type: "trait", options: ["dramatic", "bold", "oversized"] },
      preferred: { type: "trait", options: ["patterned", "spotted"], chance: 0.8, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.7 },
    },
  },
  {
    id: "all-polished-office",
    archetypes: "all",
    unlockWeek: 1,
    framing: "Something composed and polished would suit the room.",
    strategy: {
      required: { type: "trait", options: ["easygoing", "glossy", "architectural"] },
      preferred: { type: "trait", options: ["upright", "compact"], chance: 0.65, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.55 },
    },
  },
  {
    id: "all-rare-feeling",
    archetypes: "all",
    unlockWeek: 3,
    framing: "It need not be rare, only feel like a discovery.",
    strategy: {
      required: { type: "trait", options: ["strange", "collectible", "spotted"] },
      preferred: { type: "trait", options: ["miniature", "sculptural"], chance: 0.8, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.8 },
    },
  },
  {
    id: "beginner-forgiving",
    archetypes: ["beginner"],
    unlockWeek: 1,
    framing: "I forget things sometimes, so forgiving is essential.",
    strategy: {
      required: { type: "trait", options: ["easygoing", "sturdy"] },
      preferred: { type: "trait", options: ["upright", "compact"], chance: 0.6, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.3 },
    },
  },
  {
    id: "beginner-first-success",
    archetypes: ["beginner"],
    unlockWeek: 1,
    framing: "I want my first plant to feel like a small success.",
    strategy: {
      required: { type: "trait", options: ["easygoing", "compact"] },
      preferred: { type: "trait", options: ["lush", "round-leaved"], chance: 0.7, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.45 },
    },
  },
  {
    id: "decorator-room-anchor",
    archetypes: ["decorator"],
    unlockWeek: 2,
    framing: "The room needs a visual anchor, not an afterthought.",
    strategy: {
      required: { type: "trait", options: ["bold", "dramatic"] },
      preferred: { type: "trait", options: ["tall", "oversized"], chance: 0.75, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.8 },
    },
  },
  {
    id: "decorator-layered-texture",
    archetypes: ["decorator"],
    unlockWeek: 1,
    framing: "I am layering textures and need leaves with a clear point of view.",
    strategy: {
      required: { type: "trait", options: ["round-leaved", "patterned"] },
      preferred: { type: "trait", options: ["glossy", "trailing"], chance: 0.8, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.65 },
    },
  },
  {
    id: "small-space-narrow-ledge",
    archetypes: ["small-space"],
    unlockWeek: 1,
    framing: "It has to live on a narrow ledge without taking over.",
    strategy: {
      required: { type: "trait", options: ["compact", "upright"] },
      preferred: { type: "trait", options: ["miniature", "round-leaved"], chance: 0.7, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.35 },
    },
  },
  {
    id: "small-space-look-up",
    archetypes: ["small-space"],
    unlockWeek: 1,
    framing: "Floor space is gone, so I am looking upward.",
    strategy: {
      required: { type: "trait", options: ["trailing"] },
      preferred: { type: "trait", options: ["sculptural", "lush"], chance: 0.75, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.5 },
    },
  },
  {
    id: "practical-reliable",
    archetypes: ["practical"],
    unlockWeek: 1,
    framing: "Reliable beats fussy every time.",
    strategy: {
      required: { type: "trait", options: ["sturdy", "easygoing"] },
      preferred: { type: "trait", options: ["upright", "glossy"], chance: 0.6, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.3 },
    },
  },
  {
    id: "practical-clear-signals",
    archetypes: ["practical"],
    unlockWeek: 2,
    framing: "Clear care signals are more useful to me than drama.",
    strategy: {
      required: { type: "trait", options: ["thirst-teller", "easygoing"] },
      preferred: { type: "trait", options: ["architectural", "compact"], chance: 0.65, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.45 },
    },
  },
  {
    id: "collector-unusual-form",
    archetypes: ["collector"],
    unlockWeek: 2,
    framing: "I am missing an unusual silhouette from my collection.",
    strategy: {
      required: { type: "trait", options: ["sculptural", "strange", "spotted"] },
      preferred: { type: "trait", options: ["collectible", "patterned"], chance: 0.85, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.85 },
    },
  },
  {
    id: "collector-new-category",
    archetypes: ["collector"],
    unlockWeek: 2,
    framing: "Show me a form my shelves do not already have.",
    strategy: {
      required: { type: "trait", options: ["flowering", "feathery", "architectural"] },
      preferred: { type: "trait", options: ["dramatic", "miniature"], chance: 0.75, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.8 },
    },
  },
  {
    id: "sun-seeker-hot-window",
    archetypes: ["sun-seeker"],
    unlockWeek: 1,
    framing: "My brightest window needs someone who will enjoy it.",
    strategy: {
      required: { type: "trait", options: ["sunny", "sturdy"] },
      preferred: { type: "trait", options: ["sculptural", "compact"], chance: 0.7, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.5 },
    },
  },
  {
    id: "sun-seeker-bright-statement",
    archetypes: ["sun-seeker"],
    unlockWeek: 1,
    framing: "I want the sunlight to turn it into a statement.",
    strategy: {
      required: { type: "trait", options: ["sunny", "bold"] },
      preferred: { type: "trait", options: ["flowering", "tall"], chance: 0.7, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.7 },
    },
  },
  {
    id: "gift-giver-cheerful",
    archetypes: ["gift-giver"],
    unlockWeek: 2,
    framing: "It should feel cheerful the moment the paper comes off.",
    strategy: {
      required: { type: "trait", options: ["flowering", "round-leaved"] },
      preferred: { type: "trait", options: ["easygoing", "compact"], chance: 0.8, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.6 },
    },
  },
  {
    id: "gift-giver-memorable",
    archetypes: ["gift-giver"],
    unlockWeek: 2,
    framing: "I want a gift they will remember after the card is gone.",
    strategy: {
      required: { type: "trait", options: ["patterned", "strange"] },
      preferred: { type: "trait", options: ["sculptural", "spotted"], chance: 0.75, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.75 },
    },
  },
  {
    id: "office-keeper-desk-friend",
    archetypes: ["office-keeper"],
    unlockWeek: 2,
    framing: "A tidy desk plant would improve the working day.",
    strategy: {
      required: { type: "trait", options: ["compact", "easygoing"] },
      preferred: { type: "trait", options: ["upright", "round-leaved"], chance: 0.7, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.4 },
    },
  },
  {
    id: "office-keeper-reception",
    archetypes: ["office-keeper"],
    unlockWeek: 3,
    framing: "Reception needs something polished enough to greet everyone.",
    strategy: {
      required: { type: "trait", options: ["glossy", "tall", "graceful"] },
      preferred: { type: "trait", options: ["architectural", "lush"], chance: 0.75, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.75 },
    },
  },
  {
    id: "maximalist-jungle-layer",
    archetypes: ["maximalist"],
    unlockWeek: 3,
    framing: "The jungle needs another layer of leaves.",
    strategy: {
      required: { type: "trait", options: ["lush", "feathery", "oversized"] },
      preferred: { type: "trait", options: ["trailing", "bold"], chance: 0.8, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.75 },
    },
  },
  {
    id: "maximalist-pattern-stack",
    archetypes: ["maximalist"],
    unlockWeek: 3,
    framing: "More pattern is the only sensible answer.",
    strategy: {
      required: { type: "trait", options: ["patterned", "dramatic", "spotted"] },
      preferred: { type: "trait", options: ["flowering", "oversized"], chance: 0.8, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.8 },
    },
  },
  {
    id: "careful-carer-daily-ritual",
    archetypes: ["careful-carer"],
    unlockWeek: 3,
    framing: "I enjoy noticing what a plant needs each day.",
    strategy: {
      required: { type: "trait", options: ["thirst-teller", "flowering"] },
      preferred: { type: "trait", options: ["graceful", "patterned"], chance: 0.75, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.65 },
    },
  },
  {
    id: "careful-carer-training-project",
    archetypes: ["careful-carer"],
    unlockWeek: 5,
    framing: "I would love a small specimen I can shape over time.",
    strategy: {
      required: { type: "trait", options: ["miniature", "collectible"] },
      preferred: { type: "trait", options: ["sculptural", "glossy"], chance: 0.8, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.8 },
    },
  },
  {
    id: "bargain-hunter-best-value",
    archetypes: ["bargain-hunter"],
    unlockWeek: 4,
    framing: "I want dependable greenery and a sensible price.",
    strategy: {
      required: { type: "trait", options: ["easygoing", "sturdy"] },
      preferred: { type: "trait", options: ["compact", "upright"], chance: 0.55, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.2 },
    },
  },
  {
    id: "bargain-hunter-big-impact",
    archetypes: ["bargain-hunter"],
    unlockWeek: 4,
    framing: "What gives me the biggest visual impact for my coins?",
    strategy: {
      required: { type: "trait", options: ["bold", "dramatic", "tall"] },
      preferred: { type: "trait", options: ["lush", "glossy"], chance: 0.6, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.3 },
    },
  },
  {
    id: "connoisseur-specimen",
    archetypes: ["connoisseur"],
    unlockWeek: 5,
    framing: "I am here for a specimen worth studying closely.",
    strategy: {
      required: { type: "trait", options: ["collectible", "miniature", "spotted"] },
      preferred: { type: "trait", options: ["sculptural", "glossy"], chance: 0.9, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.9 },
    },
  },
  {
    id: "connoisseur-understated",
    archetypes: ["connoisseur"],
    unlockWeek: 5,
    framing: "I prefer rarity that whispers rather than shouts.",
    strategy: {
      required: { type: "trait", options: ["architectural", "graceful", "sculptural"] },
      preferred: { type: "trait", options: ["glossy", "feathery"], chance: 0.85, distinctFromRequired: true },
      budget: { type: "customer-range", position: 0.85 },
    },
  },
];

export const SLOT_DATA = [
  { x: -4.65, y: 1.12, z: -4.32, size: 0.75, ceilingY: 2.37, zone: "lowerShelf", zoneLabel: "lower shelf", lightLevel: "shade" },
  { x: -2.85, y: 1.12, z: -4.32, size: 0.75, ceilingY: 2.37, zone: "lowerShelf", zoneLabel: "lower shelf", lightLevel: "shade" },
  { x: -4.65, y: 2.55, z: -4.32, size: 0.68, zone: "upperShelf", zoneLabel: "upper shelf", lightLevel: "indirect" },
  { x: -2.85, y: 2.55, z: -4.32, size: 0.68, zone: "upperShelf", zoneLabel: "upper shelf", lightLevel: "indirect" },
  { x: 1.2, y: 0.06, z: -3.85, size: 0.9, zone: "window", zoneLabel: "sunny window", lightLevel: "sun" },
  { x: -1.3, y: 0.06, z: -2.85, size: 0.9, zone: "floor", zoneLabel: "open floor", lightLevel: "indirect" },
  { x: -3.7, y: 0.06, z: 0.2, size: 0.9, zone: "floor", zoneLabel: "open floor", lightLevel: "shade" },
  { x: 2.35, y: 1.4, z: 1.25, size: 0.72, zone: "counter", zoneLabel: "front counter", lightLevel: "indirect" },
  { x: -5.15, y: 1.12, z: -2.9, size: 0.75, ceilingY: 2.37, zone: "communityShelfLower", zoneLabel: "community wall lower shelf", lightLevel: "shade", requiresExpansion: "display-shelves" },
  { x: -5.15, y: 1.12, z: -1.3, size: 0.75, ceilingY: 2.37, zone: "communityShelfLower", zoneLabel: "community wall lower shelf", lightLevel: "shade", requiresExpansion: "display-shelves" },
  { x: -5.15, y: 2.55, z: -2.9, size: 0.68, zone: "communityShelfUpper", zoneLabel: "community wall upper shelf", lightLevel: "indirect", requiresExpansion: "display-shelves" },
  { x: -5.15, y: 2.55, z: -1.3, size: 0.68, zone: "communityShelfUpper", zoneLabel: "community wall upper shelf", lightLevel: "indirect", requiresExpansion: "display-shelves" },
];

export const SUPPLIER_TYPES = [
  {
    id: "reliable-tray",
    name: "Reliable Tray",
    description: "Three healthy, familiar plants with a balanced mix of care needs.",
    quantity: { min: 3, max: 3 },
    pricing: {
      basis: "sum-wholesale-cost",
      multiplier: 1,
      flatFee: 0,
      rounding: "nearest-coin",
    },
    selection: {
      mode: "balanced",
      reveal: "species",
      avoidDuplicates: true,
      condition: "healthy",
    },
  },
  {
    id: "curated-pair",
    name: "Curated Pair",
    description: "Two previewed plants chosen to suit today's homes and display opportunities.",
    quantity: { min: 2, max: 2 },
    pricing: {
      basis: "sum-wholesale-cost",
      multiplier: 1.15,
      flatFee: 1,
      rounding: "nearest-coin",
    },
    selection: {
      mode: "customer-and-display-fit",
      reveal: "species-and-traits",
      avoidDuplicates: true,
      condition: "healthy",
    },
  },
  {
    id: "mystery-rescue-lot",
    name: "Mystery Rescue Lot",
    description: "Three discounted mystery plants with nursery stress and reduced sale value. Rehabilitate restores their full value.",
    quantity: { min: 3, max: 3 },
    pricing: {
      basis: "sum-wholesale-cost",
      multiplier: 0.6,
      flatFee: 0,
      rounding: "nearest-coin",
    },
    selection: {
      mode: "mystery-rescue",
      reveal: "count-only",
      avoidDuplicates: false,
      condition: "stressed",
      rareChance: 0.15,
    },
  },
];
