export const SAVE_VERSION = 4;

export const CARES = ["water", "mist", "prune"];

export const INVENTORY_CAPACITY = 12;

export const SPECIES = [
  {
    id: "button-fern",
    name: "Button Fern",
    traits: ["lush", "shade-loving"],
    price: 18,
    wholesaleCost: 9,
    shape: "fern",
    color: 0x5e945a,
    dryRate: 0.24,
    preferredLight: "shade",
    toleratedLight: ["indirect"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist", "prune"],
  },
  {
    id: "velvet-pothos",
    name: "Velvet Pothos",
    traits: ["trailing", "easygoing"],
    price: 20,
    wholesaleCost: 10,
    shape: "vine",
    color: 0x567a45,
    dryRate: 0.14,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "average",
    beneficialCare: ["water", "prune"],
  },
  {
    id: "pinstripe-calathea",
    name: "Pinstripe Calathea",
    traits: ["dramatic", "patterned"],
    price: 24,
    wholesaleCost: 12,
    shape: "fan",
    color: 0x386549,
    dryRate: 0.22,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist"],
  },
  {
    id: "pocket-succulent",
    name: "Pocket Succulent",
    traits: ["sunny", "sturdy"],
    price: 16,
    wholesaleCost: 8,
    shape: "succulent",
    color: 0x83a984,
    dryRate: 0.06,
    preferredLight: "sun",
    toleratedLight: ["indirect"],
    preferredHumidity: "dry",
    beneficialCare: ["water"],
  },
  {
    id: "little-monstera",
    name: "Little Monstera",
    traits: ["bold", "lush"],
    price: 26,
    wholesaleCost: 13,
    shape: "broad",
    color: 0x3d8050,
    dryRate: 0.17,
    preferredLight: "indirect",
    toleratedLight: ["shade"],
    preferredHumidity: "high",
    beneficialCare: ["water", "mist", "prune"],
  },
  {
    id: "snake-plant",
    name: "Snake Plant",
    traits: ["upright", "easygoing"],
    price: 22,
    wholesaleCost: 11,
    shape: "spear",
    color: 0x718b3c,
    dryRate: 0.07,
    preferredLight: "indirect",
    toleratedLight: ["shade", "sun"],
    preferredHumidity: "dry",
    beneficialCare: ["water", "prune"],
  },
  {
    id: "moon-cactus",
    name: "Moon Cactus",
    traits: ["strange", "sunny"],
    price: 28,
    wholesaleCost: 14,
    shape: "cactus",
    color: 0x4f8c67,
    dryRate: 0.045,
    preferredLight: "sun",
    toleratedLight: ["indirect"],
    preferredHumidity: "dry",
    beneficialCare: ["water"],
  },
];

export const CUSTOMERS = [
  { name: "Mina", color: 0xe39a7b, line: "My windowsill needs a little courage." },
  { name: "Basil", color: 0x7189a6, line: "I promised myself I could keep one alive." },
  { name: "Jo", color: 0xd3a64b, line: "My bookshelf is looking emotionally vacant." },
  { name: "Nori", color: 0x8f74a8, line: "I want a roommate who enjoys silence." },
  { name: "Pip", color: 0x6d9a78, line: "Something peculiar, but polite, please." },
  { name: "Sol", color: 0xc9785e, line: "The sunniest corner of my flat is lonely." },
];

export const SLOT_DATA = [
  { x: -4.65, y: 1.12, z: -4.32, size: 0.75, ceilingY: 2.37, zone: "lowerShelf", zoneLabel: "lower shelf", lightLevel: "shade" },
  { x: -2.85, y: 1.12, z: -4.32, size: 0.75, ceilingY: 2.37, zone: "lowerShelf", zoneLabel: "lower shelf", lightLevel: "shade" },
  { x: -4.65, y: 2.55, z: -4.32, size: 0.68, zone: "upperShelf", zoneLabel: "upper shelf", lightLevel: "indirect" },
  { x: -2.85, y: 2.55, z: -4.32, size: 0.68, zone: "upperShelf", zoneLabel: "upper shelf", lightLevel: "indirect" },
  { x: 1.2, y: 0.06, z: -3.85, size: 0.9, zone: "window", zoneLabel: "sunny window", lightLevel: "sun" },
  { x: -1.3, y: 0.06, z: -2.85, size: 0.9, zone: "floor", zoneLabel: "open floor", lightLevel: "indirect" },
  { x: -3.7, y: 0.06, z: 0.2, size: 0.9, zone: "floor", zoneLabel: "open floor", lightLevel: "shade" },
  { x: 2.35, y: 1.4, z: 1.25, size: 0.72, zone: "counter", zoneLabel: "front counter", lightLevel: "indirect" },
];

export const SUPPLIER_TYPES = [
  {
    id: "reliable-tray",
    name: "Reliable Tray",
    description: "Three healthy, familiar plants with a balanced mix of care needs.",
    quantity: { min: 3, max: 3 },
    pricing: {
      basis: "sum-wholesale-cost",
      multiplier: 1,
      flatFee: 0,
      rounding: "nearest-coin",
    },
    selection: {
      mode: "balanced",
      reveal: "species",
      avoidDuplicates: true,
      condition: "healthy",
    },
  },
  {
    id: "curated-pair",
    name: "Curated Pair",
    description: "Two previewed plants chosen to suit today's homes and display opportunities.",
    quantity: { min: 2, max: 2 },
    pricing: {
      basis: "sum-wholesale-cost",
      multiplier: 1.15,
      flatFee: 1,
      rounding: "nearest-coin",
    },
    selection: {
      mode: "customer-and-display-fit",
      reveal: "species-and-traits",
      avoidDuplicates: true,
      condition: "healthy",
    },
  },
  {
    id: "mystery-rescue-lot",
    name: "Mystery Rescue Lot",
    description: "Three discounted mystery plants that arrive stressed but can recover with thoughtful care.",
    quantity: { min: 3, max: 3 },
    pricing: {
      basis: "sum-wholesale-cost",
      multiplier: 0.6,
      flatFee: 0,
      rounding: "nearest-coin",
    },
    selection: {
      mode: "mystery-rescue",
      reveal: "count-only",
      avoidDuplicates: false,
      condition: "stressed",
      rareChance: 0.15,
    },
  },
];
